### ISSUE TITLE
Link on location field

### ISSUE THREAD

**Issue by chanil1218** [penicillin0/atcoder-add-calender#1]
These days, it is common to set URL on location field of the schedule. 
It would be nice to change the default behavior of the pasting URL. 

I much appreciated your clean simple extension for AtCoder! 
Thanks! 

I hope it will be integrated into the AtCoder site natively.

**Comment by penicillin0** [comment]
@chanil1218 
Thank you very much for your kind suggestion.
I have changed the default URL placement from details to location.
Please update it if you like.
https://greasyfork.org/ja/scripts/390758-atcoder-google-calender

**Comment by penicillin0** [comment]
The chrome extension is under review. I will close this issue as soon as the review passes.

**Comment by penicillin0** [comment]
Since the chrome extension has passed the review and has been released successfully, I am closing this issue.
Thank you for your contribution.
https://chrome.google.com/webstore/detail/atcoder-calendar/dokfhaljgioiaeappgnmibgoipegbldf
